trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Firstjob
    steps:
    - bash: echo build Firstjob
    - bash: echo $(xvariable)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourceDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: java -version
    - bash: node --version
    - bash: python --version
    - bash: mvn -version
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
  # - job: Secondjob
  #   steps:
  #   - bash: echo build Firstjob
# - stage: DevDeploy
#   dependsOn: Build
#   variables:
#     environment: Dev
#   jobs:
#   - job: DevDeployJob
#     steps:
#     - bash: echo build $(environment)Deploy
# - stage: QADeploy
#   dependsOn: Build
#   jobs:
#   - job: QADeploy
#     steps:
#     - bash: echo build Firstjob
# - stage: ProdDeploy
#   dependsOn:
#   - QADeploy
#   - DevDeploy
#   jobs:
#   - job: Prodjob
#     steps:
#     - bash: echo build Prodjob