trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Firstjob
    steps:
    - bash: echo build Firstjob
  - job: Secondjob
    steps:
    - bash: echo build Firstjob
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo build DevDeploy
- stage: QADeploy
  jobs:
  - job: QADeploy
    steps:
    - bash: echo build Firstjob
- stage: ProdDeploy
  dependsOn:
  - QADeploy
  - DevDeploy
  jobs:
  - job: Prodjob
    steps:
    - bash: echo build Prodjob